backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
media_folder: "static/img" # Media files will be stored in the repo under static/images/uploads
public_folder: "/img" # The src attribute for uploa
collections:
  - name: "projects" # Used in routes, e.g., /admin/collections/blog
    label: "Projects" # Used in the UI
    folder: "content/projects" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    extension: mdx
    format: frontmatter
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "cover", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "site"
    label: "Site"
    editor:
      preview: false
    files:
      - file: "/config/site.js"
        label: "Site configuration"
        name: "config"
        fields:
          - {label: "Site Title", name: "siteTitle"}
          - {label: "Site Title (Alt)", name: "siteTitleAlt"}
          - {label: "Site Title Short", name: "siteTitleShort"}
          - {label: "Site Headline", name: "siteHeadline"}
          - {label: "Site URL", name: "siteUrl"}
          - {label: "Site Language", name: "siteLanguage"}
          - {label: "Site Logo", name: "siteLogo"}
          - {label: "Site Description", name: "siteDescription"}
          - {label: "Author", name: "author"}

          - {label: "Facebook App ID", name: "siteFBAppID"}
          - {label: "Twitter Handle", name: "userTwitter"}
          - {label: "ogSiteName", name: "ogSiteName"}
          - {label: "ogLanguage", name: "ogLanguage"}
          - {label: "googleAnalyticsID", name: "googleAnalyticsID"}

          # Date format used in your project
          # More information here: https://date-fns.org/v1.29.0/docs/format
          # - {label: "dateFormat", name: "dateFormat"}

          # Manifest and Progress color
          - {label: "Theme Color", name: "themeColor"}
          - {label: "Background Color", name: "backgroundColor"}

          # # Settings for typography.js
          # - {label: "headerFontFamily", name: "headerFontFamily"}
          # - {label: "bodyFontFamily", name: "bodyFontFamily"}
          # - {label: "baseFontSize", name: "baseFontSize"}

          # Your information
          - {label: "Avatar", name: "avatar"} # @todo image ?
          - {label: "Name", name: "name"}
          - {label: "Location", name: "location"}
          - {label: "Social Media", name: "socialMedia", widget: "list", fields: [{label: Name, name: name}, {label: Url, name: url}]}
